name: projectbia
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.3.0 
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.0.0
  flutter_svg: ^2.0.10 # atau versi terbaru
  carousel_slider: ^4.2.1
  flutter_staggered_grid_view: ^0.6.1
  shared_preferences: ^2.5.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_image.png  # Pastikan gambar ini ada di folder assets/images
    - assets/images/laskarpelangi.jpg  # Pastikan gambar ini ada di folder assets/images

flutter_native_splash:
  color: "#ffffff"  # Background color splash screen
  image: assets/images/splash_image.png  # Gambar logo splash screen (opsional)
  android: true
  ios: true
  web: true